project:
  type: website

website:
  title: "stats-learn"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css
bibliography: references.bib
csl: american-medical-association.csl
editor: visual

